### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by aziz-boudi4** [stepanhruda/dyld-image-loading-performance#4]
I followed all the steps and everything worked fine in a sample project, but when I wanted to try it in my App I kept having a `Linker command failed with exit code 1`

Here is the error

`ld: -filelist file '/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos-armv7.objects.filelist' could not be opened, errno=2 (No such file or directory)`

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any Idea what might be the problem ?

**Comment by stepanhruda** [comment]
The `*.filelist` isn't getting generated. Can you make sure that the script from step 2 is getting executed? Try adding `puts intermediates_directory` there and seeing what the directory structure looks like in that directory.

It's possible that `Pods.build` might need to be changed to `Pods-YourTargetName.build`

**Comment by aziz-boudi4** [comment]
The script is being executed but i'm getting this error : 

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/MyProject.build/Debug-iphoneos/Staging.build/Script-8F6283261C5855AC003DC010.sh: line 4: intermediates_directory: command not found`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/MyProject.build/Debug-iphoneos/Staging.build/Script-8F6283261C5855AC003DC010.sh: line 6: configuration: command not found`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/MyProject.build/Debug-iphoneos/Staging.build/Script-8F6283261C5855AC003DC010.sh: line 7: platform: command not found`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/MyProject.build/Debug-iphoneos/Staging.build/Script-8F6283261C5855AC003DC010.sh: line 8: archs: command not found`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/MyProject.build/Debug-iphoneos/Staging.build/Script-8F6283261C5855AC003DC010.sh: line 10: syntax error near unexpected token`" "'`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/MyProject.build/Debug-iphoneos/Staging.build/Script-8F6283261C5855AC003DC010.sh: line 10:`archs.split(" ").each do |architecture|'`

`Command /bin/sh failed with exit code 2`

**Comment by stepanhruda** [comment]
Do you have Ruby installed? Can you post the build step from which you are executing the script?

**Comment by aziz-boudi4** [comment]
Yes Ruby is installed.
![screen shot 2016-01-26 at 8 22 19 pm](https://cloud.githubusercontent.com/assets/7435015/12603791/8ae2a270-c46a-11e5-871a-23db167cbc5e.png)

Here is the build step:
![screen shot 2016-01-26 at 8 19 47 pm](https://cloud.githubusercontent.com/assets/7435015/12603778/6f60228e-c46a-11e5-83a1-db7ed80d5f8f.png)

**Comment by stepanhruda** [comment]
Move the [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) (`#!/usr/bin/ruby`) into the `Shell` field, like this:

<img width="152" alt="screen shot 2016-01-26 at 11 27 05 pm" src="https://cloud.githubusercontent.com/assets/2835783/12603869/55f7355c-c484-11e5-9c3c-0e9ba0bdd91c.png">

**Comment by aziz-boudi4** [comment]
Thanks for the help:

`/bin/sh: /Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/MyProject.build/Debug-iphoneos/Staging.build/Script-8F6283261C5855AC003DC010.sh: usr/bin/ruby: bad interpreter: No such file or directory`

**Comment by stepanhruda** [comment]
You forgot the leading slash (`/` before `usr`). Also, you don't need the shebang at the beginning of the script anymore in case you left it there.

**Comment by aziz-boudi4** [comment]
I'm getting 53 errors : 
Did I forget any step:

`ld: warning: Auto-Linking supplied '/Users/Me/ios-app/MyProject/Pods/Fabric/iOS/Fabric.framework/Fabric', framework linker option at /Users/Me/ios-app/MyProject/Pods/Fabric/iOS/Fabric.framework/Fabric is not a dylib
Undefined symbols for architecture armv7:``

`"_sqlite3_column_blob", referenced from:`

```
  -[AWSFMResultSet dataForColumnIndex:] in AWSFMResultSet.o

  -[AWSFMResultSet dataNoCopyForColumnIndex:] in AWSFMResultSet.o
```

 `"_sqlite3_column_type", referenced from:`

```
  -[AWSFMResultSet stringForColumnIndex:] in AWSFMResultSet.o

  -[AWSFMResultSet dateForColumnIndex:] in AWSFMResultSet.o

  -[AWSFMResultSet dataForColumnIndex:] in AWSFMResultSet.o`
```

.................
`ld: symbol(s) not found for architecture armv7`

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by stepanhruda** [comment]
You need to manually link your app target against sqlite3

**Comment by aziz-boudi4** [comment]
So I should link all the libraries that appeared in the error message using the build step `Link Binary with Libraries`?

**Comment by stepanhruda** [comment]
Only the system libraries, all 3rd party dependencies coming from Cocoapods are handled by the workaround.

**Comment by aziz-boudi4** [comment]
Great thanks for your time I will try that.

**Comment by aziz-boudi4** [comment]
I got rid of most of the errors that I had by linking the system libraries manually, but I'm having errors related to 3rd party dependencies.
Do I have to change something in my code ?

`ld: warning: Auto-Linking supplied '/Users/Me/ios-app/MyProject/Pods/Fabric/iOS/Fabric.framework/Fabric', framework linker option at /Users/Me/ios-app/MyProject/Pods/Fabric/iOS/Fabric.framework/Fabric is not a dylib``

  `"_TWTROAuthEchoAuthorizationHeaderKey", referenced from:`

```
  `static Staging.Session.authenticate (Staging.Session.Type)(__ObjC.DGTSession) -> PromiseKit.Promise<()> in Session.o`
```

 `"_OBJC_CLASS_$_DGTOAuthSigning", referenced from:`

```
`  type metadata accessor for __ObjC.DGTOAuthSigning in Session.o`
```

 `"_OBJC_CLASS_$_DGTAuthenticationConfiguration", referenced from:`

```
 ` type metadata accessor for __ObjC.DGTAuthenticationConfiguration in Twitter.o`
```

 `"_OBJC_CLASS_$_TWTRSession", referenced from:`

```
 ` type metadata accessor for __ObjC.TWTRSession in UserSearchController.o`
```

 `"_CLSLogv", referenced from:`

```
  `Staging.CrashlyticsLogDestination.(output (Staging.CrashlyticsLogDestination) -> (XCGLogger.XCGLogDetails, text : Swift.String) -> ()).(closure #1) in Globals.o`
```

 `"_OBJC_CLASS_$_Intercom", referenced from:`

```
  `type metadata accessor for __ObjC.Intercom in WearableContainerController.o`
```

 `"_OBJC_CLASS_$_Fabric", referenced from:`

```
 ` type metadata accessor for __ObjC.Fabric in AppDelegate.o`
```

 `"_OBJC_CLASS_$_Twitter", referenced from:`

```
  `type metadata accessor for __ObjC.Twitter in UserSearchController.o`


  `l__CATEGORY_Twitter_$_Staging in Twitter.o`
```

 `"_OBJC_CLASS_$_DGTAppearance", referenced from:`

```
  `type metadata accessor for __ObjC.DGTAppearance in Twitter.o`
```

  `"_OBJC_CLASS_$_Digits", referenced from:`

```
 ` type metadata accessor for __ObjC.Digits in AppDelegate.o`
```

  `"_TWTROAuthEchoRequestURLStringKey", referenced from:`

```
 ` static Staging.Session.authenticate (Staging.Session.Type)(__ObjC.DGTSession) -> PromiseKit.Promise<()> in Session.o`
```

 `"_OBJC_CLASS_$_Crashlytics", referenced from:`

```
  `type metadata accessor for __ObjC.Crashlytics in AppDelegate.o`
```

  `"_OBJC_CLASS_$_Answers", referenced from:`

```
  `type metadata accessor for __ObjC.Answers in Api.o`
```

 `"_OBJC_CLASS_$_DGTSession", referenced from:`

```
 ` l__CATEGORY_DGTSession_$_Staging in Twitter.o`


  `type metadata accessor for __ObjC.DGTSession in Twitter.o`
```

`ld: symbol(s) not found for architecture armv7`

`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by stepanhruda** [comment]
What does the generated `.filelist` look like?

**Comment by aziz-boudi4** [comment]
Where can I find the generated .filelist ?
is it this one 
![screen shot 2016-01-27 at 11 40 41 am](https://cloud.githubusercontent.com/assets/7435015/12625961/019beb08-c4eb-11e5-88ab-27fadcda0cc5.png)

**Comment by stepanhruda** [comment]
Nope, it will be deep in the DerivedData folder: `/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos-armv7.objects.filelist`

**Comment by aziz-boudi4** [comment]
it has 400 lines of files 
here are the first few lines:
`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/armv7/AWSBolts.o`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/armv7/AWSCategory.o`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/armv7/AWSClientContext.o`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/armv7/AWSCognitoIdentityModel.o`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/armv7/AWSCognitoIdentityResources.o`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/armv7/AWSCognitoIdentityService.o`

`/Users/Me/Library/Developer/Xcode/DerivedData/MyProject-daztnjxoamygucaztfkjqbzhhxwc/Build/Intermediates/Pods.build/Debug-iphoneos/AWSCore.build/Objects-normal/armv7/AWSCore-dummy.o``

**Comment by stepanhruda** [comment]
Looking at the output again – it seems that Fabric is shipped as a binary framework. Unfortunately you have to ignore it and link it manually as noted by the workaround:

>  This only works if you are compiling the framework from source.

**Comment by aziz-boudi4** [comment]
Do you know how to fix this error ?
`Undefined symbols for architecture armv7:``

The only errors left start with  `"_OBJC_CLASS_$_.........`

`"_TWTROAuthEchoAuthorizationHeaderKey", referenced from:`
      `static Staging.Session.authenticate (Staging.Session.Type)(__ObjC.DGTSession) -> PromiseKit.Promise<()> in Session.o`
 `"_OBJC_CLASS_$_DGTOAuthSigning", referenced from:
      type metadata accessor for __ObjC.DGTOAuthSigning in Session.o`
  `"_OBJC_CLASS_$_DGTAuthenticationConfiguration", referenced from:
      type metadata accessor for __ObjC.DGTAuthenticationConfiguration in Twitter.o`
  `"_OBJC_CLASS_$_TWTRSession", referenced from:
      type metadata accessor for __ObjC.TWTRSession in UserSearchController.o`

**Comment by stepanhruda** [comment]
Which library do these symbols come from? They are prefixed with `TWTRSession` is that Fabric, or do you have another Twitter library?

**Comment by aziz-boudi4** [comment]
I have another Twitter libraries like DIGITS for authentication,  
another error comes from Intercom ( a tool for communication with  users),
Crashlytics is giving an error too.

here is the list of libraries that are giving errors : 

  `"_TWTROAuthEchoAuthorizationHeaderKey", referenced from:
      static Staging.Session.authenticate (Staging.Session.Type)(__ObjC.DGTSession) -> PromiseKit.Promise<()> in Session.o``

`"_OBJC_CLASS_$_DGTOAuthSigning", referenced from:
      type metadata accessor for __ObjC.DGTOAuthSigning in Session.o``

`"_OBJC_CLASS_$_DGTAuthenticationConfiguration", referenced from:
      type metadata accessor for __ObjC.DGTAuthenticationConfiguration in Twitter.o``

`"_OBJC_CLASS_$_TWTRSession", referenced from:
      type metadata accessor for __ObjC.TWTRSession in UserSearchController.o``

`"_CLSLogv", referenced from:
      Staging.CrashlyticsLogDestination.(output (Staging.CrashlyticsLogDestination) -> (XCGLogger.XCGLogDetails, text : Swift.String) -> ()).(closure #1) in Globals.o``

`"_OBJC_CLASS_$_Intercom", referenced from:
      type metadata accessor for __ObjC.Intercom in WearableContainerController.o``

`"_OBJC_CLASS_$_Fabric", referenced from:
      type metadata accessor for __ObjC.Fabric in AppDelegate.o``

`"_OBJC_CLASS_$_Twitter", referenced from:
      type metadata accessor for __ObjC.Twitter in UserSearchController.o``

`l__CATEGORY_Twitter_$_Staging in Twitter.o
  "_OBJC_CLASS_$_DGTAppearance", referenced from:
      type metadata accessor for __ObjC.DGTAppearance in Twitter.o``

`"_OBJC_CLASS_$_Digits", referenced from:
      type metadata accessor for __ObjC.Digits in AppDelegate.o``

`"_TWTROAuthEchoRequestURLStringKey", referenced from:
      static Staging.Session.authenticate (Staging.Session.Type)(__ObjC.DGTSession) -> PromiseKit.Promise<()> in Session.o``

`"_OBJC_CLASS_$_Crashlytics", referenced from:
      type metadata accessor for __ObjC.Crashlytics in AppDelegate.o``

`"_OBJC_CLASS_$_Answers", referenced from:
      type metadata accessor for __ObjC.Answers in Api.o``

`"_OBJC_CLASS_$_DGTSession", referenced from:
      l__CATEGORY_DGTSession_$_Staging in Twitter.o
      type metadata accessor for __ObjC.DGTSession in Twitter.o``

**Comment by stepanhruda** [comment]
The same restrictions apply as mentioned above – you cannot use the workaround for these, because you only have the binary and are not compiling them from source. You have to link them manually in your Xcode project.

**Comment by aziz-boudi4** [comment]
Ok thank you very much for your help
